version: '3.8'

services:
  app:
    build: .
    image: teacher-portfolio-app:latest
    container_name: teacher-app
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/teacher_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - teacher-network

  db:
    image: postgres:13-alpine
    container_name: teacher-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=teacher_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d teacher_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - teacher-network

volumes:
  postgres_data:

networks:
  teacher-network:
    driver: bridge